name: Deploy trading_app_backend to AWS

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Deploy to EC2
        run: |
          echo "Deploying branch: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" == "main" ]]; then
            CONTAINER_NAME="trade-sense-backend"
            IMAGE_NAME="trade-sense-app"
            PORT="5000"
          elif [[ "$BRANCH_NAME" == "dev" ]]; then
            CONTAINER_NAME="trade-sense-backend-dev"
            IMAGE_NAME="trade-sense-app-dev"
            PORT="5001"
          else
            echo "Unsupported branch: $BRANCH_NAME"
            exit 1
          fi
          
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << EOF
            set -e
            cd ~
            
            BRANCH_NAME="$BRANCH_NAME"
            CONTAINER_NAME="$CONTAINER_NAME"
            IMAGE_NAME="$IMAGE_NAME"
            PORT="$PORT"
            
            if [ ! -d "Trade-Sense-App-backend-" ]; then
              git clone https://github.com/ghulammujtaba153/Trade-Sense-App-backend-.git
            fi

            cd Trade-Sense-App-backend-
            git fetch origin \$BRANCH_NAME
            git checkout \$BRANCH_NAME
            git pull origin \$BRANCH_NAME

            docker rm -f \$CONTAINER_NAME || true
            docker build -t \$IMAGE_NAME .

            if [ "\$BRANCH_NAME" = "main" ]; then
              ENV_FILE=".env.main"
            else
              ENV_FILE=".env.dev"
            fi

            echo "Using env file: \$ENV_FILE"

            docker run -d \
              --name \$CONTAINER_NAME \
              --env-file \$ENV_FILE \
              -p 0.0.0.0:\$PORT:5000 \
              \$IMAGE_NAME
          EOF
