name: Deploy trading_app_backend to AWS

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        BRANCH_NAME="${GITHUB_REF##*/}"

        # Dynamic container name and port
        if [[ "$BRANCH_NAME" == "main" ]]; then
          CONTAINER_NAME="trade-sense-backend"
          IMAGE_NAME="trade-sense-app"
          PORT="5000"
        elif [[ "$BRANCH_NAME" == "dev" ]]; then
          CONTAINER_NAME="trade-sense-backend-dev"
          IMAGE_NAME="trade-sense-app-dev"
          PORT="5001"
        else
          echo "Unsupported branch: $BRANCH_NAME"
          exit 1
        fi

        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << EOF
          set -e

          # Clone repo if it doesn't exist
          if [ ! -d ~/Trade-Sense-App-backend ]; then
            https://github.com/ghulammujtaba153/Trade-Sense-App-backend-
          fi

          cd ~/Trade-Sense-App-backend

          # Fetch & checkout correct branch
          git fetch origin $BRANCH_NAME
          git checkout $BRANCH_NAME
          git pull origin $BRANCH_NAME

          # Stop and remove existing container
          docker rm -f $CONTAINER_NAME || true

          # Build image
          docker build -t $IMAGE_NAME .

          # Run container on branch-specific port
          docker run -d \
            --name $CONTAINER_NAME \
            --env-file .env \
            -p 127.0.0.1:$PORT:5000 \
            $IMAGE_NAME
        EOF
